services:
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: 'rest-api'
            POSTGRES_USER: 'restapi'
            POSTGRES_PASSWORD: 'restapi'
        volumes:
            - ./database:/var/lib/postgresql/data
        ports:
            - '5432:5432'


